### ISSUE TITLE
Plugin not reloading in QGIS 3?

### ISSUE THREAD

**Issue by ar-jan** [borysiasty/plugin_reloader#11]
I'm currently learning how to build a plugin. I used Plugin Builder to create a plugin skeleton. After modifying the plugin, compiling and deploying it with pb_tool, reloading it with this module seems to do nothing.

I created the custom plugin with Plugin Builder  - just filled out the required fields, with a menu entry under Database. Compiled and deployed it, and the menu item and dialog show up. Then I added a textfield with Qt Creator, recompiled and deployed the custom module. Reloading the custom module does not do anything (afaict), but after restarting QGIS, the custom module's dialog is changed to the updated version.

plugin_reloader version is 0.7.2, with QGIS 2.99.0-master of a couple of days ago.

**Comment by borysiasty** [comment]
When you run the reloading, do you get a confirmation message "<your-plugin-name> reloaded" ?
If you see the message, but don't notice any change, it seems the reloader fails to work. If you don't see the message, it seems it's didn't run at all.

**Comment by ar-jan** [comment]
I didn't see the message...

**Comment by borysiasty** [comment]
If you go to the Plugins -> Plugin reloader menu, do you see your plugin name after the "Reload plugin:" words? 

![zrzut_20180124_101046](https://user-images.githubusercontent.com/1000043/35323749-ead4d6e0-00ee-11e8-8a17-51a307f6929e.png)

If so, please try to use that menu entry rather than the keyboard shortcut - maybe it's in a conflict with map redrawing. 
If not, use the next option to configure the reloader.

**Comment by ar-jan** [comment]
OK so this was just UI confusion on my part. I used "Choose a plugin to be reloaded" and expected that to do a reload. It's working correctly. Thanks!

**Comment by borysiasty** [comment]
Good point, I'll rename it to "configure". Thanks!
