### ISSUE TITLE
F5 shortcut out of work

### ISSUE THREAD

**Issue by fuzzysolutions** [borysiasty/plugin_reloader#15]
Since a certain QGIS version (2.18.15 still worked, my new installation of 2.18.21 (LTR) and 3.2.0 (current release) does not), the F5 shortcut for plugin reloader is in conflict with a QGIS-internal shortcut ("Refresh"). Pressing F5 calls this refresh only. Using the "Reload plugin" menu button in still works.

Workaround: In "Set shortcuts ..." dialogue, I set "Refresh" to Ctrl+F5 (as I don't really use it), freeing F5 for plugin reloader.

**Comment by borysiasty** [comment]
I'm going to set Ctrl-F5 for the plugin, but with possibility to easily swap those shortcuts with one click.

**Comment by borysiasty** [comment]
Fixed in 0.6.5 (for QGIS 2) and 0.7.4 (for QGIS 3). The shortcut is now set to Ctrl+F5 and you can change it in the "Keyboard Shortcuts" window.

Finally I didn't implement any one-click helper, as making the shortcut properly configurable from the "Keyboard Shortcuts" window surprisingly occurred to be laborious enough: https://github.com/borysiasty/plugin_reloader/blob/master/reloader_plugin.py#L67-L74
