### ISSUE TITLE
Reloading causes Processing to raise an Error

### ISSUE THREAD

**Issue by borysiasty** [borysiasty/plugin_reloader#6]
_Moved from http://hub.qgis.org/issues/10121
Bug report #10121, added by @Martin-Jung, 2014-04-26._

Hi,

I am not sure if this is a bug should be fixed within the Processing Toolbox or the PluginReloader plugin (which I just found and find highly useful).

Iam just developing a new Plugin for QGIS that adds several new functions for the Processing Toolbox. Unfortunately whenever I reload the plugin via the PluginReloader and try to open my new custom ProcessingFunctions it raises the following error (see attached Screenshot). The error disappears if I reload the Processing Providers. This can be done by simply open the Processing Options menu and closing it again. 
Maybe a small routine in the PluginReloader tool can be implemented that reloads all ProcessingProviders as well.

Tested on QGIS 2.2, Linux - Debian 64bit

![screen](https://cloud.githubusercontent.com/assets/1000043/17960693/e83c27fa-6aa7-11e6-8afc-cc68388ca21f.png)

**Comment by borysiasty** [comment]
_Discussion_

@borysiasty wrote: 

> Could you please provide some steps (a sample change in the code) to reproduce this bug?

@Martin-Jung wrote:

> Don't know what you mean with code samples, but here is how to reproduce with QGIS 2.2 stable (tested on Debian Jessie)
> 1. Download for instance the Animove Plugin or LecoS plugin which has Processing features
> 2. Enable the plugin and make sure it is visible and executable in the Processing Toolbox
> 3. Select the Plugin in the PluginReloader for Reload
> 4. Reload the plugin
> 5. Now directly attempt to start the Plugin from the Processing Toolbox. Error shown in the screen- shot should occur.

**Comment by borysiasty** [comment]
See also #20.

**Comment by kobben** [comment]
[copied here my comment from #20 because that was closed and found no way to re-open it:

Got the same problem of processing plugin not reloading. In a email conversation found that yquenach@itlink.fr concluded the problem apparently occurs if the plugin python file has the same name as its containing folder [which is normally the case, because that's the way that the Plugin Builder delivers its output. Tested and can confirm. If you eg rename the folder holding the processing plugin files from plugin_name to folder_plugin_name , the reloading works fine...

**Comment by borysiasty** [comment]
This particular problem seems to be no longer valid. Today's error should be fixed with 36537d3864261 (soon to be released)
